[package]
name = "cart"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[dependencies]
wasmstation = { git = "https://github.com/wasmstation/wasmstation", branch = "implement-precompiled", crate = "wasmstation" }
