[package]
name = "wasmstation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# general
anyhow = "1.0"
bytemuck = "1.12"

# wgpu
winit = { version = "0.27", optional = true, default-features = false, features = ["x11"] }
wgpu = { version = "0.14", optional = true }
pollster = { version = "0.2", optional = true }
byteorder = "1.4.3"

# wasmer
wasmer = { version = "3.0", optional = true }

# cli
argh = { version = "0.1", optional = true }

[features]
default = ["wasmer-backend", "wgpu-renderer"] # this is still up for debate obviously
wgpu-renderer = ["wgpu", "winit", "pollster"]
# sdl2-backend = []
wasmer-backend = ["wasmer"]
# wasm3-backend = []
cli = ["argh", "winit"]

[[bin]]
name = "wasmstation"
path = "src/bin/cli.rs"
required-features = ["cli"]