[package]
name = "wasmstation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# general
anyhow = "1.0"
bytemuck = "1.12"

# wgpu
wgpu = { version = "0.14", optional = true }
winit = { version = "0.27", optional = true, default-features = false, features = ["x11"] }
pollster = { version = "0.2", optional = true }
byteorder = "1.4.3"

# cli
argh = { version = "0.1", optional = true }

[features]
default = ["wasmer", "wgpu-renderer"] # this is still up for debate obviously

wgpu-renderer = ["wgpu", "winit", "pollster"]
render-sdl = []
# embedded-graphics = []

wasmer = []
# wasm3 = []

cli = ["argh"]

[[bin]]
name = "wasmstation"
path = "src/bin/cli.rs"
required-features = ["cli"]
