[package]
name = "wasmstation-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1"
wasmstation = { path = "../wasmstation", features = ["wasmer-backend"] }

[features]
default = ["sdl2"]

wgpu = ["wasmstation/wgpu-renderer"]
sdl2 = ["wasmstation/sdl2-renderer"]

[[bin]]
name = "wasmstation"
path = "src/main.rs"