[package]
name = "wasmstation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# general
anyhow = "1.0"
bytemuck = "1.12"

# wgpu
winit = { version = "0.27", optional = true, default-features = false, features = ["x11"] }
wgpu = { version = "0.14", optional = true }
pollster = { version = "0.2", optional = true }
byteorder = "1.4.3"

# wasmer
wasmer = { version = "3.0", optional = true }

# sdl2
sdl2 = { version = "0.35", optional = true }

[features]
default = [
    "wasmer-backend", 
    "wgpu-renderer", 
    "sdl2-renderer",
] # this is still up for debate obviously
wgpu-renderer = ["wgpu", "winit", "pollster"]
sdl2-renderer = ["sdl2"]
wasmer-backend = ["wasmer"]
# wasm3-backend = []

[dev-dependencies]
argh = "0.1"