name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev

    - name: Cache
      uses: actions/cache@v2.1.8
      with:
        key: ${{ runner.os }}-wasmstation
        path: target/ Cargo.lock

    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose

    - name: Run tests
      run: cargo test --verbose
